version = 1

[envs.ripgrep]
channels = ["conda-forge"]
dependencies = { ripgrep = "*" }
exposed = { rg = "rg" }

[envs.fd-find]
channels = ["conda-forge"]
dependencies = { fd-find = "*" }
exposed = { fd = "fd" }

[envs.esptool]
channels = ["conda-forge"]
dependencies = { esptool = "*" }
exposed = { esp_rfc2217_server = "esp_rfc2217_server", espefuse = "espefuse", espsecure = "espsecure", esptool = "esptool" }

[envs.visidata]
channels = ["conda-forge"]
dependencies = { visidata = "*" }
exposed = { vd = "vd", "vd2to3.vdx" = "vd2to3.vdx", visidata = "visidata" }
